import type { ServiceItem } from "@/types";
import { ServiceItemStatus } from "@/types/service-item-status";

export const DEFAULT_SERVICES_DATA: ServiceItem[] = [
  {
    id: 1,
    title: 'Plumbing',
    description: 'Pipe repairs, leak fixes, installations',
    priceMin: 500,
    priceMax: 2000,
    ratePerKm: 25,
    iconName: 'mdi:wrench',
    iconColor: '#04697D',
    iconTextColor: '#80d8d6',
    status: ServiceItemStatus.Active,
    subServiceItems: [
      {
        id: 1,
        serviceItemId: 1,
        title: 'Leak Repair',
        description: 'Professional repair of water leaks in pipes, faucets, and fixtures. Includes diagnosis, replacement of damaged components, and testing to ensure proper water flow.',
        iconName: 'mdi:water',
        cost: 200,
        fee: 300,
        gross: 500,
        status: ServiceItemStatus.Active,
      },
      {
        id: 2,
        serviceItemId: 1,
        title: 'Pipe Installation',
        description: 'Complete installation of new water supply and drainage pipes. Includes material supply, proper fitting, and connection to existing plumbing systems.',
        iconName: 'mdi:pipe',
        cost: 400,
        fee: 600,
        gross: 1000,
        status: ServiceItemStatus.Active,
      },
      {
        id: 3,
        serviceItemId: 1,
        title: 'Toilet Repair & Installation',
        description: 'Repair or replace broken toilets for better functionality.',
        iconName: 'mdi:toilet',
        cost: 250,
        fee: 150,
        gross: 400,
        status: ServiceItemStatus.Active,
      },
      {
        id: 4,
        serviceItemId: 1,
        title: 'Water Heater Repair & Installation',
        description: 'Service or replace water heaters to ensure reliable hot water.',
        iconName: 'mdi:water-boiler',
        cost: 400,
        fee: 200,
        gross: 600,
        status: ServiceItemStatus.Active,
      },
      {
        id: 5,
        serviceItemId: 1,
        title: 'Sump Pump Installation & Repair',
        description: 'Install or repair sump pumps to prevent basement flooding.',
        iconName: 'mdi:water-pump',
        cost: 300,
        fee: 180,
        gross: 480,
        status: ServiceItemStatus.Active,
      },
      {
        id: 6,
        serviceItemId: 1,
        title: 'Faucet Repair/Replacement',
        description: 'Repair or replacement of leaking or damaged faucets. Includes diagnosis, installation of new parts, and ensuring proper water flow.',
        iconName: 'mdi:faucet',
        cost: 200,
        fee: 300,
        gross: 500,
        status: ServiceItemStatus.Active,
      },
      {
        id: 7,
        serviceItemId: 1,
        title: 'Sewer Line Inspection/Repair',
        description: 'Inspection and repair of sewer lines to prevent blockages, leaks, and foul odors. May include camera inspection and pipe replacement if needed.',
        iconName: 'mdi:magnify',
        cost: 500,
        fee: 400,
        gross: 900,
        status: ServiceItemStatus.Active,
      },
      {
        id: 8,
        serviceItemId: 1,
        title: 'Shower & Bathtub Installation/Repair',
        description: 'Installation or repair of showers and bathtubs, including plumbing connections, sealing, and leak prevention.',
        iconName: 'mdi:shower',
        cost: 800,
        fee: 600,
        gross: 1400,
        status: ServiceItemStatus.Active,
      },
      {
        id: 9,
        serviceItemId: 1,
        title: 'Garbage Disposal Repair/Installation',
        description: 'Repair or installation of garbage disposal units to ensure efficient kitchen waste management and drainage.',
        iconName: 'mdi:delete',
        cost: 300,
        fee: 300,
        gross: 600,
        status: ServiceItemStatus.Active,
      },
    ],
  },
  {
    id: 2,
    title: 'Electrical',
    description: 'Wiring, outlets, lighting repairs',
    priceMin: 400,
    priceMax: 1500,
    ratePerKm: 25,
    iconName: 'mdi:flash',
    iconColor: '#04697D',
    iconTextColor: '#80d8d6',
    status: ServiceItemStatus.Active,
    subServiceItems: [
      {
        id: 10,
        serviceItemId: 2,
        title: 'Outlet Replacement',
        description: 'Safe replacement of electrical outlets and switches. Includes removal of old fixtures, proper wiring, and installation of new outlets with safety testing.',
        iconName: 'mdi:power-plug',
        cost: 150,
        fee: 250,
        gross: 400,
        status: ServiceItemStatus.Active,
      },
      {
        id: 11,
        serviceItemId: 2,
        title: 'Lighting Setup',
        description: 'Professional installation of indoor and outdoor lighting fixtures. Includes wiring, mounting, and configuration of switches and dimmers.',
        iconName: 'mdi:lightbulb',
        cost: 300,
        fee: 400,
        gross: 700,
        status: ServiceItemStatus.Active,
      },
    ],
  },
  {
    id: 3,
    title: 'Carpentry',
    description: 'Furniture repair, installations',
    priceMin: 600,
    priceMax: 2500,
    ratePerKm: 30,
    iconName: 'mdi:hammer',
    iconColor: '#04697D',
    iconTextColor: '#80d8d6',
    status: ServiceItemStatus.Active,
    subServiceItems: [
      {
        id: 12,
        serviceItemId: 3,
        title: 'Door & Cabinet',
        description: 'Installation and repair of doors and cabinet systems. Includes hanging, alignment, hardware installation, and finishing touches.',
        iconName: 'mdi:door',
        cost: 120,
        fee: 180,
        gross: 300,
        status: ServiceItemStatus.Active,
      },
      {
        id: 13,
        serviceItemId: 3,
        title: 'Shelving Install',
        description: 'Custom shelving installation for storage solutions. Includes measuring, cutting, mounting, and securing shelves to walls or existing structures.',
        iconName: 'mdi:bookshelf',
        cost: 120,
        fee: 150,
        gross: 270,
        status: ServiceItemStatus.Active,
      },
      {
        id: 14,
        serviceItemId: 3,
        title: 'Furniture Repair',
        description: 'Restoration and repair of wooden furniture. Includes fixing joints, replacing damaged parts, and refinishing surfaces.',
        iconName: 'mdi:sofa',
        cost: 120,
        fee: 160,
        gross: 280,
        status: ServiceItemStatus.Active,
      },
      {
        id: 15,
        serviceItemId: 3,
        title: 'Trim/Molding',
        description: 'Installation of decorative trim and molding around doors, windows, and baseboards. Includes cutting, fitting, and finishing work.',
        iconName: 'mdi:square-outline',
        cost: 120,
        fee: 140,
        gross: 260,
        status: ServiceItemStatus.Active,
      },
      {
        id: 16,
        serviceItemId: 3,
        title: 'Wood Repairs',
        description: 'General wood repair services including patching holes, replacing damaged boards, and structural wood maintenance.',
        iconName: 'mdi:tools',
        cost: 120,
        fee: 130,
        gross: 250,
        status: ServiceItemStatus.Active,
      },
      {
        id: 17,
        serviceItemId: 3,
        title: 'Door Fixing',
        description: 'Comprehensive door repair services including alignment, hardware replacement, weatherstripping, and lock installation.',
        iconName: 'mdi:door-open',
        cost: 300,
        fee: 200,
        gross: 500,
        status: ServiceItemStatus.Active,
      },
    ],
  },
  {
    id: 4,
    title: 'Painting',
    description: 'Interior/exterior painting',
    priceMin: 800,
    priceMax: 3000,
    ratePerKm: 30,
    iconName: 'tabler:paint-filled',
    iconColor: '#04697D',
    iconTextColor: '#80d8d6',
    status: ServiceItemStatus.Active,
    subServiceItems: [
      {
        id: 18,
        serviceItemId: 4,
        title: 'Room Repaint',
        description: 'Complete room painting service including surface preparation, primer application, and two coats of premium paint. Includes cleanup and furniture protection.',
        iconName: 'mdi:brush',
        cost: 500,
        fee: 700,
        gross: 1200,
        status: ServiceItemStatus.Active,
      },
    ],
  },
  {
    id: 5,
    title: 'Appliance Repair',
    description: 'AC, refrigerator, washing machine',
    priceMin: 700,
    priceMax: 2800,
    ratePerKm: 28,
    iconName: 'mdi:tools',
    iconColor: '#04697D',
    iconTextColor: '#80d8d6',
    status: ServiceItemStatus.Active,
    subServiceItems: [
      {
        id: 19,
        serviceItemId: 5,
        title: 'AC Repair',
        description: 'Air conditioning system diagnosis and repair. Includes troubleshooting, component replacement, refrigerant servicing, and performance testing.',
        iconName: 'mdi:air-conditioner',
        cost: 600,
        fee: 400,
        gross: 1000,
        status: ServiceItemStatus.Active,
      },
    ],
  },
  {
    id: 6,
    title: 'Security',
    description: 'CCTV, locks, alarm systems',
    priceMin: 1000,
    priceMax: 4000,
    ratePerKm: 25,
    iconName: 'mdi:shield',
    iconColor: '#04697D',
    iconTextColor: '#80d8d6',
    status: ServiceItemStatus.Active,
    subServiceItems: [
      {
        id: 20,
        serviceItemId: 6,
        title: 'CCTV Setup',
        description: 'Complete CCTV surveillance system installation including camera mounting, wiring, DVR/NVR setup, and mobile app configuration for remote monitoring.',
        iconName: 'mdi:cctv',
        cost: 800,
        fee: 1200,
        gross: 2000,
        status: ServiceItemStatus.Active,
      },
    ],
  },
  {
    id: 7,
    title: 'Home Maintenance',
    description: 'Dryer vent cleaning, chimney cleaning, seasonal maintenance, and other home upkeep services.',
    priceMin: 1000,
    priceMax: 4000,
    ratePerKm: 28,
    iconName: 'mdi:home',
    iconColor: '#04697D',
    iconTextColor: '#80d8d6',
    status: ServiceItemStatus.Active,
    subServiceItems: [
      {
        id: 21,
        serviceItemId: 7,
        title: 'Dryer Vent Cleaning',
        description: 'Thorough cleaning of dryer vents to improve efficiency, prevent fires, and extend appliance lifespan.',
        iconName: 'mdi:air-filter',
        cost: 80,
        fee: 120,
        gross: 200,
        status: ServiceItemStatus.Active,
      },
      {
        id: 22,
        serviceItemId: 7,
        title: 'Chimney Cleaning & Inspection',
        description: 'Professional chimney sweeping and safety inspection to prevent blockages and ensure proper ventilation.',
        iconName: 'mdi:fireplace',
        cost: 100,
        fee: 150,
        gross: 250,
        status: ServiceItemStatus.Active,
      },
      {
        id: 23,
        serviceItemId: 7,
        title: 'Chimney Repair',
        description: 'Repair of damaged bricks, mortar joints, and chimney caps to restore safety and functionality.',
        iconName: 'mdi:hammer-wrench',
        cost: 200,
        fee: 200,
        gross: 400,
        status: ServiceItemStatus.Active,
      },
      {
        id: 24,
        serviceItemId: 7,
        title: 'Gutter Cleaning',
        description: 'Removal of leaves, debris, and blockages from gutters and downspouts to ensure proper water drainage.',
        iconName: 'mdi:broom',
        cost: 80,
        fee: 120,
        gross: 200,
        status: ServiceItemStatus.Active,
      },
      {
        id: 25,
        serviceItemId: 7,
        title: 'Gutter Repair & Installation',
        description: 'Repair of leaking or damaged gutters and installation of new systems to improve water flow.',
        iconName: 'mdi:home-roof',
        cost: 150,
        fee: 180,
        gross: 330,
        status: ServiceItemStatus.Active,
      },
      {
        id: 26,
        serviceItemId: 7,
        title: 'Pressure Washing',
        description: 'High-pressure cleaning for driveways, decks, siding, and other surfaces to remove dirt, grime, and mold.',
        iconName: 'mdi:water-pump',
        cost: 100,
        fee: 150,
        gross: 250,
        status: ServiceItemStatus.Active,
      },
      {
        id: 27,
        serviceItemId: 7,
        title: 'Window Cleaning',
        description: 'Interior and exterior window washing for streak-free clarity and improved curb appeal.',
        iconName: 'mdi:window-closed',
        cost: 60,
        fee: 90,
        gross: 150,
        status: ServiceItemStatus.Active,
      },
      {
        id: 28,
        serviceItemId: 7,
        title: 'Handyman Services',
        description: 'General repair and maintenance tasks for home upkeep, including minor fixes and installations.',
        iconName: 'mdi:hammer',
        cost: 80,
        fee: 120,
        gross: 200,
        status: ServiceItemStatus.Active,
      },
      {
        id: 29,
        serviceItemId: 7,
        title: 'Furniture Assembly',
        description: 'Assembly of flat-pack and custom furniture, including bed frames, desks, cabinets, and shelves.',
        iconName: 'mdi:package-variant',
        cost: 60,
        fee: 100,
        gross: 160,
        status: ServiceItemStatus.Active,
      },
      {
        id: 30,
        serviceItemId: 7,
        title: 'Home Weatherproofing',
        description: 'Sealing gaps, insulating windows/doors, and installing weatherstripping to improve energy efficiency.',
        iconName: 'mdi:shield',
        cost: 120,
        fee: 180,
        gross: 300,
        status: ServiceItemStatus.Active,
      },
      {
        id: 31,
        serviceItemId: 7,
        title: 'Garage Door Repair & Installation',
        description: 'Repair and installation of garage doors, openers, and related hardware.',
        iconName: 'mdi:garage',
        cost: 300,
        fee: 250,
        gross: 550,
        status: ServiceItemStatus.Active,
      },
      {
        id: 32,
        serviceItemId: 7,
        title: 'Fence Repair & Installation',
        description: 'Repair and construction of wood, vinyl, and metal fencing for security and privacy.',
        iconName: 'mdi:fence',
        cost: 200,
        fee: 300,
        gross: 500,
        status: ServiceItemStatus.Active,
      },
      {
        id: 33,
        serviceItemId: 7,
        title: 'Deck Repair & Installation',
        description: 'Repair, staining, and construction of wooden decks for durability and aesthetics.',
        iconName: 'mdi:deck',
        cost: 250,
        fee: 350,
        gross: 600,
        status: ServiceItemStatus.Active,
      },
      {
        id: 34,
        serviceItemId: 7,
        title: 'Pool Maintenance & Repair',
        description: 'Cleaning, chemical balancing, and repair of pool systems for safe and clear water.',
        iconName: 'mdi:pool',
        cost: 150,
        fee: 200,
        gross: 350,
        status: ServiceItemStatus.Active,
      },
      {
        id: 35,
        serviceItemId: 7,
        title: 'Appliance Installation',
        description: 'Installation of major household appliances including washers, dryers, refrigerators, and ovens.',
        iconName: 'mdi:stove',
        cost: 100,
        fee: 150,
        gross: 250,
        status: ServiceItemStatus.Active,
      },
      {
        id: 36,
        serviceItemId: 7,
        title: 'Appliance Repair',
        description: 'Repair services for malfunctioning household appliances, restoring them to working condition.',
        iconName: 'mdi:wrench',
        cost: 120,
        fee: 180,
        gross: 300,
        status: ServiceItemStatus.Active,
      },
      {
        id: 37,
        serviceItemId: 7,
        title: 'Smoke & Carbon Monoxide Detector Installation',
        description: 'Installation and testing of smoke and CO detectors for improved home safety.',
        iconName: 'mdi:smoke-detector',
        cost: 50,
        fee: 80,
        gross: 130,
        status: ServiceItemStatus.Active,
      },
      {
        id: 38,
        serviceItemId: 7,
        title: 'Smart Home Device Installation',
        description: 'Setup of smart home devices such as thermostats, cameras, lighting systems, and security devices.',
        iconName: 'mdi:home-automation',
        cost: 80,
        fee: 120,
        gross: 200,
        status: ServiceItemStatus.Active,
      },
    ],
  },
];